-- Active: 1712300046689@@127.0.0.1@1433@SalesCo
CREATE OR ALTER FUNCTION PRICE_AFTER_DISCOUNT(
    @PRODUCT_ID VARCHAR(10) = NULL
) RETURNS NUMERIC(9,2)
AS 
BEGIN
    DECLARE @PRODUCT_PRICE NUMERIC(9,2);
    DECLARE @PRODUCT_DISCOUNT NUMERIC(9,2);

    SELECT 
        @PRODUCT_PRICE = P_PRICE, 
        @PRODUCT_DISCOUNT = P_DISCOUNT
    FROM 
        PRODUCT 
    WHERE 
        P_CODE = @PRODUCT_ID;

    RETURN @PRODUCT_PRICE - (@PRODUCT_PRICE * @PRODUCT_DISCOUNT);
END;