-- Active: 1709917766724@@127.0.0.1@1433@SaleCo@dbo
-- No.1
SELECT 
	C.CUS_CODE, 
    I.INV_NUMBER, 
    I.INV_DATE, 
    P.P_DESCRIPT,
    L.LINE_UNITS, 
    L.LINE_PRICE 
FROM CUSTOMER C 
JOIN INVOICE I 
	ON C.CUS_CODE = I.CUS_CODE
JOIN LINE L 
	ON I.INV_NUMBER = L.INV_NUMBER
JOIN PRODUCT P 
	ON L.P_CODE = P.P_CODE
ORDER BY 
	C.CUS_CODE;
	
-- No.2
SELECT 
	C.CUS_CODE, 
    I.INV_NUMBER, 
    P.P_DESCRIPT,
    L.LINE_UNITS, 
    L.LINE_PRICE,
    L.LINE_UNITS * L.LINE_PRICE AS SUB_TOTAL
FROM CUSTOMER C 
JOIN INVOICE I 
	ON C.CUS_CODE = I.CUS_CODE
JOIN LINE L 
	ON I.INV_NUMBER = L.INV_NUMBER
JOIN PRODUCT P 
	ON L.P_CODE = P.P_CODE
ORDER BY 
	C.CUS_CODE;
	
-- No.3
SELECT 
	C.CUS_CODE,
	SUM(L.LINE_PRICE * L.LINE_UNITS) AS TOTAL_PURCHASES
FROM CUSTOMER C 
JOIN INVOICE I 
	ON C.CUS_CODE = I.CUS_CODE
JOIN LINE L 
	ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY 
	C.CUS_CODE
ORDER BY 
	C.CUS_CODE;
	
-- No.4
SELECT 
	C.CUS_CODE,
	C.CUS_LNAME,
	C.CUS_BALANCE,
	SUM(L.LINE_PRICE * L.LINE_UNITS) AS TOTAL_PURCHASES
FROM CUSTOMER C 
JOIN INVOICE I 
	ON C.CUS_CODE = I.CUS_CODE
JOIN LINE L 
	ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY 
	C.CUS_CODE,
	C.CUS_LNAME,
	C.CUS_BALANCE
ORDER BY 
	C.CUS_CODE;

-- No. 5
SELECT 
	C.CUS_CODE,
	C.CUS_LNAME,
	C.CUS_BALANCE,
	SUM(L.LINE_PRICE * L.LINE_UNITS) AS TOTAL_PURCHASES,
	SUM(L.LINE_UNITS) AS UNIT_PURCHASED,
	AVG(L.LINE_PRICE) AS AVG_UNIT_PRICE_PURCHASED
FROM CUSTOMER C 
JOIN INVOICE I 
	ON C.CUS_CODE = I.CUS_CODE
JOIN LINE L 
	ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY 
	C.CUS_CODE,
	C.CUS_LNAME,
	C.CUS_BALANCE
ORDER BY 
	C.CUS_CODE;

-- No. 6
SELECT 
	I.INV_NUMBER,
	SUM(L.LINE_PRICE * L.LINE_UNITS) AS INVOICE_TOTAL 
FROM CUSTOMER C 
JOIN INVOICE I 
	ON C.CUS_CODE = I.CUS_CODE
JOIN LINE L 
	ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY 
	I.INV_NUMBER;

-- No. 7
SELECT 
	C.CUS_CODE,
	C.CUS_BALANCE 
FROM CUSTOMER C
WHERE EXISTs (
	SELECT I.CUS_CODE 
	FROM INVOICE I 
	WHERE I.CUS_CODE = C.CUS_CODE
)