-- Active: 1709917766724@@127.0.0.1@1433@SaleCo@dbo
ALTER TABLE PRODUCT 
ADD REORDER NUMERIC(1) NULL;

CREATE OR ALTER TRIGGER UPDATESTOCK ON LINE 
FOR INSERT 
AS 
BEGIN
    DECLARE @BOUGHT INT;
    SELECT @BOUGHT = LINE_UNITS FROM INSERTED;

    UPDATE PRODUCT
    SET P_QOH = (PRODUCT.P_QOH - @BOUGHT)
    FROM INSERTED
    WHERE PRODUCT.P_CODE = INSERTED.P_CODE;
END;

CREATE OR ALTER TRIGGER RESTOCK ON PRODUCT
FOR UPDATE 
AS 
BEGIN
    DECLARE @MIN INT, @QOH INT;
    SELECT @MIN = P_MIN, @QOH = P_QOH FROM INSERTED;
    IF (@QOH > @MIN) RETURN;
    
    UPDATE PRODUCT 
    SET REORDER = 1
    FROM INSERTED
    WHERE PRODUCT.P_CODE = INSERTED.P_CODE;
END;
